"""
Data schemas and models for Delta VTuber Personal Presence System.
"""

import time
from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, field_validator


class PresenceActivity(str, Enum):
    IDLE = "IDLE"
    LISTENING = "LISTENING"
    THINKING = "THINKING"
    WORKING = "WORKING"
    SPEAKING = "SPEAKING"
    WAITING = "WAITING"
    ERROR = "ERROR"


class NotificationType(str, Enum):
    TASK_COMPLETE = "TASK_COMPLETE"
    TASK_FAILED = "TASK_FAILED"
    IMPORTANT_RESULT = "IMPORTANT_RESULT"
    USER_RETURNED = "USER_RETURNED"


class PresenceState(BaseModel):
    """
    State representing Delta's personal desktop awareness and attention level.
    """
    online: bool = True
    activity: PresenceActivity = PresenceActivity.IDLE
    last_interaction: float = Field(default_factory=time.time)
    idle_duration: float = 0.0
    attention_level: float = Field(default=0.8, ge=0.0, le=1.0)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @field_validator("attention_level", mode="before")
    @classmethod
    def clamp_attention(cls, v: Any) -> float:
        try:
            return max(0.0, min(1.0, float(v)))
        except (ValueError, TypeError):
            return 0.5


class NotificationEvent(BaseModel):
    """
    Internal notification generated by background tasks or companion presence.
    """
    notification_type: NotificationType
    title: str
    message: str
    timestamp: float = Field(default_factory=time.time)
    metadata: Dict[str, Any] = Field(default_factory=dict)
